### ISSUE TITLE
getColor() function

### ISSUE THREAD

**Issue by sraimund** [heinzgnehm/MultimediaCartography#1]
Try to use a for loop for the getColor() function:
https://github.com/heinzgnehm/MultimediaCartography/blob/master/scripts/crime.js#L84-L94

You can store the colors in an array and access them via the index while iterating the grades array. This separates code from data and makes the code reusable.

**Comment by heinzgnehm** [comment]
I have changed the respective code. The colors are now stored in an array and the functions loops through the grades array to find the matching color.
